### ISSUE TITLE
Unhandled error when closing document

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1813]
Steps to repro: 
1. Create a new document.
2. Close the document.

```
Action documents.close failed: TypeError: Cannot read property 'id' of null
    at eval (file://./js/jsx/PanelSet.jsx:171:68)
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1165:46
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:3642:58
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1915:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:2264:11)
    at src_Map__Map.__iterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1913:32)
    at src_Set__Set.__iterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:3642:24)
    at SetIterable.mappedSequence.__iterateUncached (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1164:23)
    at seqIterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:593:16)
    at SetIterable.Seq.__iterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:261:14)
    at SetIterable.mixin.forEach (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4327:19)
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:3536:16
    at src_Set__Set.src_Map__Map.withMutations (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1891:7)
    at new src_Set__Set (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:3533:20)
    at reify (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1704:37)
    at src_Set__Set.mixin.map (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4347:14)
From previous event:
    at Object.disposeDocument (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:431:14)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:304:36)
    at Object.FluxController._makeActionReceiver.Object.create.transfer.value (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:239:33)
    at Object.close (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:323:29)
From previous event:
    at Object.close (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:322:14)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:304:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:399:37)
From previous event:
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:395:22)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:292:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:144:14)
    at Object.FluxController._synchronize (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:378:42)
    at Object.throttledFn (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/synchronization.js:66:31)
    at Object.playMenuCommand (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/menu.js:223:9)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/menu.js:320:29)
    at emitEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:380:50)
    at emit (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:407:21)
    at UI._menuEventHandler (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/ui.js:90:14)
```

**Comment by chadrolfs** [comment]
related to #1684
