### ISSUE TITLE
CC Lib: dragging asset with Opt/Alt key to place expanded layers results in error

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1944]
new doc, load a library that has an asset that contains multiple layers, drag + alt/opt onto canvas
Result: ```Action layers.addLayers failed: Error: Replacing a layer but the new layer's index seems out of bounds
    at Record.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/models/layerstructure.js:814:27)
    at Array.reduce (native)
    at Record.LayerStructure.addLayers (file:///Users/crolfs/playground-repos/spaces-design/src/js/models/layerstructure.js:796:41)
    at Fluxxor.createStore._handleLayerAdd (file:///Users/crolfs/playground-repos/spaces-design/src/js/stores/document.js:256:46)
    at Store.__handleAction__ (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:592:16)
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:157:41)
    at file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:2465:20
    at file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:4227:12
    at baseForOwn (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:2634:11)
    at file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:2658:13
    at Dispatcher.doDispatchLoop (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:140:4)
    at Dispatcher.dispatch (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:129:11)
    at Object.dispatchBinder.dispatch (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:269:21)
    at Object.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/actions/layers.js:301:22)
From previous event:
    at Object.addLayers (file:///Users/crolfs/playground-repos/spaces-design/src/js/actions/layers.js:292:14)
    at FluxController._applyAction (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:304:36)
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:399:37)
From previous event:
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:395:22)
    at AsyncDependencyQueue._processNext (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:292:27)
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:304:26)
From previous event:
    at AsyncDependencyQueue._processNext (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:300:21)
    at AsyncDependencyQueue.push (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:144:14)
    at Object.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:378:42)
    at eval (file://./js/jsx/Scrim.jsx:335:36)
From previous event:
    at Object.handleDropGraphic [as onDrop] (file://./js/jsx/Scrim.jsx:334:27)
    at Fluxxor.createStore.stopDrag (file:///Users/crolfs/playground-repos/spaces-design/src/js/stores/draganddrop.js:204:22)
    at React.createClass._handleDragFinish (file://./js/jsx/shared/Draggable.jsx:280:53)```

**Comment by volfied** [comment]
My merge closed it for some reason. To @chadrolfs for testing.

**Comment by chadrolfs** [comment]
Now seeing: 
```Action libraries.createLayerFromElement failed: Error: Invalid transfer from libraries.createLayerFromElement to undefined. Add undefined to the list of transfers declared for libraries.createLayerFromElement.```

maybe due to new lib changes from main?  testing on pg-dev 438

**Comment by shaoshing** [comment]
Thanks for testing. It is related to the change of locking. Second fix is coming.

**Comment by shaoshing** [comment]
:tada:
