### ISSUE TITLE
Unhandled exception in search for current documents

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2347]
1. Open a new document
2. cmd-F to search
3. type "doc"
4. Hit enter to select "Filter by current documents"
5. Unhandled exception:

```
TypeError: Cannot read property 'split' of undefined
    at Fluxxor.createStore.handleExecute (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/stores/search.js:177:33)
    at eval (file://./js/jsx/Search.jsx:76:33)
From previous event:
    at React.createClass._handleOption (file://./js/jsx/Search.jsx:74:18)
    at React.createClass._handleChange (file://./js/jsx/search/SearchBar.jsx:360:32)
    at React.createClass._handleSelectChange (file://./js/jsx/shared/Datalist.jsx:302:48)
    at React.createClass._handleSelectClick (file://./js/jsx/shared/Datalist.jsx:328:22)
    at React.createClass._handleSelectClose (file://./js/jsx/shared/Datalist.jsx:347:22)
    at React.createClass.close (file://./js/jsx/shared/Select.jsx:338:24)
    at React.createClass._handleInputKeyDown (file://./js/jsx/shared/Datalist.jsx:270:28)
    at React.createClass._handleKeyDown (file://./js/jsx/shared/TextInput.jsx:274:28)
```

**Comment by iwehrman** [comment]
Fixed by #2349.
