### ISSUE TITLE
Dragging image from browser onto canvas result in error and bad state

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2415]
cmd/ctrl + n (in DS)
switch to browser (chrome) and do an google image search (e.g. "beach")
drag an image from browser onto canvas area

Result: `Action layers.addLayers failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: 24946 Photoshop message: error: 24946 message: base element not found`

`Uncaught Error: Job canceled before execution`
`Uncaught Error: Photoshop returned an error when playing command number: 1 Photoshop code: 24946 Photoshop message: error: 24946 message: base element not found`

**Comment by volfied** [comment]
FWIW, I don't see this.

**Comment by volfied** [comment]
BUT, we need to reset borderpolicies after layerActions.addLayers

**Comment by iwehrman** [comment]
My guess is that, somehow or another, this is because the event handler is not an action.

**Comment by iwehrman** [comment]
I can repro:
```
Action layers.addLayers failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: 24946 Photoshop message: error: 24946 message: base element not found
    at eval (eval at undefined, <anonymous>:1:5)
    at eval (native)
From previous event:
    at Descriptor._batchPlayImmediate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:387:14)
    at Descriptor.batchPlay (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:519:25)
    at Descriptor.batchMultiGetProperties (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:700:21)
    at _getLayersByRef (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/layers.js:146:49)
    at Object.addLayers (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/layers.js:391:16)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:464:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:557:37)
From previous event:
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:553:22)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:536:42)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:1021:38)
    at emitEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:380:50)
    at Descriptor.emitEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:135:47)
    at emit (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:407:21)
    at Descriptor._psEventHandler (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:103:14)
```

**Comment by iwehrman** [comment]
This is a core bug. The "drag" event seems to have the wrong layer ID in the particular case of the new layer causing the previous, empty layer to be replaced. I'll file the Watson issue.

**Comment by iwehrman** [comment]
[Watson 4068448](https://watsonexp.corp.adobe.com/#bug=4068448) to @jsbache.

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4068448 Closed/Fixed, regressed in staging: pg.1662 @1047439. So far as I can tell, the ActionDescriptor returned with the notification has the correct "replaceLayer" ids.
