### ISSUE TITLE
Setting type color in modal state fails

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2418]
```
Action type.setColor failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Set” is not currently available.
    at eval (eval at undefined, <anonymous>:1:5)
    at eval (native)
From previous event:
    at Descriptor._batchPlayImmediate (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:387:14)
    at Descriptor.batchPlay (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:519:25)
    at Descriptor.batchPlayObjects (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:544:21)
    at Descriptor.playObject (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:367:21)
    at Object.playWithLockOverride (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/locking.js:144:35)
    at Object.playSimpleLayerActions (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/layeractions.js:157:36)
    at Object.setColor (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/type.js:279:48)
    at FluxController._applyAction (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.FluxController._synchronize (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at Object.throttledFn (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/synchronization.js:66:31)
    at React.createClass._handleOpaqueColorChange (file://./js/jsx/sections/style/Type.jsx:215:31)
    at React.createClass._changeColor (file://./js/jsx/shared/ColorPicker.jsx:863:24)
    at React.createClass._update (file://./js/jsx/shared/ColorPicker.jsx:817:30)
    at React.createClass._handleSaturationValueChange (file://./js/jsx/shared/ColorPicker.jsx:787:18)
    at React.createClass._updatePosition (file://./js/jsx/shared/ColorPicker.jsx:375:24)
    at DraggableMixin._startUpdates (file://./js/jsx/shared/ColorPicker.jsx:153:18)
    at React.createClass._handleMouseDown (file://./js/jsx/shared/ColorPicker.jsx:388:18)
    at Object.executeDispatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3311:21)
    at SimpleEventPlugin.executeDispatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:17428:40)
    at forEachEventDispatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3299:5)
    at Object.executeDispatchesInOrder (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3320:3)
    at executeDispatchesAndRelease (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2693:22)
    at Array.forEach (native)
    at forEachAccumulated (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:19430:9)
```

**Comment by ktaki** [comment]
The same error happens when changing the color for a drop shadow. Library panel flickers and the error above repeats many times while showing a spinner.

**Comment by volfied** [comment]
I don't see this anymore in latest master @ktaki

**Comment by ktaki** [comment]
Correct. This has been fixed by the latest Core changes.

**Comment by iwehrman** [comment]
Fixed by @jfitz-adobe.
