### ISSUE TITLE
Unhandled exception in SuperSelectOverlay

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2456]
This happened when I opened Vermilion from another document:
```
TypeError: Cannot read property 'isArtboard' of null
    at eval (file://./js/jsx/tools/SuperselectOverlay.jsx:499:68)
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4342:23
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1223:57
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:997:34
    at List.__iterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:2756:13)
    at ToKeyedSequence.__iterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:993:25)
    at KeyedIterable.reversedSequence.__iterate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1223:23)
    at KeyedIterable.mixin.findEntry (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4341:12)
    at KeyedIterable.mixin.find (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4335:24)
    at List.mixin.findLast (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4465:42)
    at eval (file://./js/jsx/tools/SuperselectOverlay.jsx:498:40)
From previous event:
    at React.createClass.updateMouseOverHighlights (file://./js/jsx/tools/SuperselectOverlay.jsx:497:18)
    at React.createClass.mouseMoveHandler (file://./js/jsx/tools/SuperselectOverlay.jsx:176:22)
    at emitEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:380:50)
    at emit (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:407:21)
    at OS._eventHandler (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/os.js:110:14)
```

**Comment by iwehrman** [comment]
Fixed by #2458.
