### ISSUE TITLE
CMD+f Errors sometimes when using this file

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2505]
Error is hard to reproduce, but seems to happen when I mulit-select a bunch of text objects that have missing fonts (Lust script), then try to open the App Search using CMD+f.

File: http://cl.ly/2O3x100N2P1E

```
Opening an un-registered dialog without providing a dismissalPolicy
js/fluxcontroller.js:563 Action search.toggleSearchBar failed: TypeError: Cannot read property 'searchItems' of undefined
    at Fluxxor.createStore.getState (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/stores/search.js:147:65)
    at React.createClass.getStateFromFlux (file://./js/jsx/search/SearchBar.jsx:60:43)
    at getInitialState (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:482:20)
    at mergedResult [as getInitialState] (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:6019:17)
    at new Constructor (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:6258:54)
    at ReactCompositeComponentMixin.mountComponent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:6791:16)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:10068:19)
    at wrapper [as mountComponent] (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13968:31)
    at Object.ReactReconciler.mountComponent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:14781:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13622:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13528:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13473:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:8388:12)
    at ReactDOMComponent.Mixin.updateComponent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:8237:10)
    at ReactDOMComponent.Mixin.receiveComponent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:8221:10)
    at Object.ReactReconciler.receiveComponent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:14840:22)
From previous event:
    at Object.create.dispatchAsync.value (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:400:44)
    at Object.openDialog (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/dialog.js:45:21)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at Object.create.transfer.value (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:387:33)
    at Object.toggleSearchBar (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/search.js:49:21)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at Object.throttledFn (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/synchronization.js:66:31)
    at Object._playMenuCommand (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/menu.js:236:9)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/menu.js:338:30)
    at emitEvent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:380:50)
    at emit (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:407:21)
    at UI._menuEventHandler (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/ui.js:90:14)
/Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/bluebird/js/browser/bluebird.js:95 Uncaught TypeError: Cannot read property 'context' of null```

**Comment by iwehrman** [comment]
I just hit the same thing. This time, there were no documents open. It also left the app in an unusable state, presumably because it thinks a modal dialog is somehow open?
```
js/fluxcontroller.js:543 Executing action search.toggleSearchBar after waiting 1ms; 1/0
js/stores/dialog.js:202 Opening an un-registered dialog without providing a dismissalPolicy
js/fluxcontroller.js:563 Action search.toggleSearchBar failed: TypeError: Cannot read property 'searchItems' of undefined
    at Fluxxor.createStore.getState (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/stores/search.js:147:65)
    at React.createClass.getStateFromFlux (file://./js/jsx/search/SearchBar.jsx:60:43)
    at getInitialState (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:482:20)
    at mergedResult [as getInitialState] (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:6019:17)
    at new Constructor (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:6258:54)
    at ReactCompositeComponentMixin.mountComponent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:6791:16)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:10068:19)
    at wrapper [as mountComponent] (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13968:31)
    at Object.ReactReconciler.mountComponent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:14781:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13622:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13528:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:13473:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:8388:12)
    at ReactDOMComponent.Mixin.updateComponent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:8237:10)
    at ReactDOMComponent.Mixin.receiveComponent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:8221:10)
    at Object.ReactReconciler.receiveComponent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:14840:22)
From previous event:
    at Object.create.dispatchAsync.value (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:400:44)
    at Object.openDialog (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/actions/dialog.js:61:36)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at Object.create.transfer.value (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:387:33)
    at Object.toggleSearchBar (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/actions/search.js:49:21)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at Object.throttledFn (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/util/synchronization.js:66:31)
    at Object._playMenuCommand (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/actions/menu.js:236:9)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/src/js/actions/menu.js:338:30)
    at emitEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:380:50)
    at emit (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:407:21)
    at UI._menuEventHandler (file:///Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/ui.js:90:14)
/Users/wehrman/Desktop/photoshop-Release_x86_64%202/Plug-Ins/Spaces/www/bower_components/bluebird/js/browser/bluebird.js:95 Uncaught TypeError: Cannot read property 'context' of null
```

**Comment by iwehrman** [comment]
I figured out how to reproduce this reliably: it happens when you search _after_ a reset. Almost certainly this means the search registration is not correctly resetting itself.

**Comment by volfied** [comment]
@placegraphichere can you confirm the fix with Ian's reproduce steps.

**Comment by iwehrman** [comment]
Kicking this over to @chadrolfs for verification.
