### ISSUE TITLE
Sampler trace errors 

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2572]
3 Error messages (may be the same issue multiple times) when attempting to sample text-to-text and shift click sample:

```
Export: Found configured port: 59596
fluxcontroller.js:553 Finished action type.initFontList in 303ms with RTT 325ms; 2/3
fluxcontroller.js:543 Executing action type.initFontList after waiting 305ms; 2/2
export.js:862 Export: Generator plugin connection established
fluxcontroller.js:553 Finished action export.afterStartup in 316ms with RTT 316ms; 2/2
fluxcontroller.js:553 Finished action type.initFontList in 193ms with RTT 498ms; 1/2
fluxcontroller.js:543 Executing action ui.afterStartup after waiting 491ms; 1/1
fluxcontroller.js:553 Finished action ui.afterStartup in 8ms with RTT 499ms; 1/1
fluxcontroller.js:543 Executing action application.afterStartup after waiting 500ms; 1/0
fluxcontroller.js:522 Enqueuing action ui.updatePanelSizes; 1/0
fluxcontroller.js:553 Finished action application.afterStartup in 113ms with RTT 613ms; 1/1
fluxcontroller.js:543 Executing action ui.updatePanelSizes after waiting 36ms; 1/0
fluxcontroller.js:553 Finished action ui.updatePanelSizes in 146ms with RTT 182ms; 1/0
fluxcontroller.js:522 Enqueuing action sampler.showHUD; 0/0
fluxcontroller.js:543 Executing action sampler.showHUD after waiting 1ms; 1/0
fluxcontroller.js:563 Action sampler.showHUD failed: TypeError: Cannot read property 'characterStyle' of null
    at Object._getSourceColor (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:77:41)
    at Object._calculateSampleTypes (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:105:32)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:403:46)
From previous event:
    at Object.showHUD (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:390:14)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at SamplerTool.onClick (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/tools/sampler.js:102:34)
    at React.createClass._handleClick (file://./js/jsx/Scrim.jsx:53:30)
    at Object.executeDispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3311:21)
    at SimpleEventPlugin.executeDispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:17428:40)
    at forEachEventDispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3299:5)
    at Object.executeDispatchesInOrder (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3320:3)
    at executeDispatchesAndRelease (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2693:22)
    at Array.forEach (native)
    at forEachAccumulated (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:19430:9)
    at Object.EventPluginHub.processEventQueue (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2900:5)
    at runEventQueueInBatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11217:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11243:5)
    at handleTopLevelImpl (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11329:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:18402:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:9669:19)
fluxcontroller.js:522 Enqueuing action ui.onReset; 1/0
fluxcontroller.js:522 Enqueuing action menu.onReset; 2/0
fluxcontroller.js:522 Enqueuing action guides.onReset; 3/0
fluxcontroller.js:522 Enqueuing action history.onReset; 4/0
fluxcontroller.js:522 Enqueuing action keyevents.onReset; 5/0
fluxcontroller.js:522 Enqueuing action layers.onReset; 6/0
fluxcontroller.js:522 Enqueuing action export.onReset; 7/0
fluxcontroller.js:522 Enqueuing action policy.onReset; 8/0
fluxcontroller.js:522 Enqueuing action shortcuts.onReset; 8/1
fluxcontroller.js:522 Enqueuing action tools.onReset; 8/2
fluxcontroller.js:522 Enqueuing action transform.onReset; 8/3
fluxcontroller.js:522 Enqueuing action documents.onReset; 8/4
fluxcontroller.js:543 Executing action ui.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action menu.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action guides.onReset after waiting 1ms; 8/5
fluxcontroller.js:543 Executing action history.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action keyevents.onReset after waiting 1ms; 8/5
fluxcontroller.js:543 Executing action layers.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action export.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action policy.onReset after waiting 8ms; 8/4```

---

```Executing action menu.beforeStartup after waiting 1ms; 8/4
fluxcontroller.js:543 Executing action history.beforeStartup after waiting 1ms; 8/4
fluxcontroller.js:543 Executing action keyevents.beforeStartup after waiting 0ms; 8/4
fluxcontroller.js:543 Executing action libraries.beforeStartup after waiting 1ms; 8/4
fluxcontroller.js:543 Executing action guides.beforeStartup after waiting 0ms; 8/4
fluxcontroller.js:543 Executing action transform.beforeStartup after waiting 0ms; 8/4
fluxcontroller.js:543 Executing action documents.beforeStartup after waiting 0ms; 8/4
fluxcontroller.js:553 Finished action menu.beforeStartup in 53ms with RTT 54ms; 8/4
fluxcontroller.js:553 Finished action history.beforeStartup in 53ms with RTT 54ms; 8/4
fluxcontroller.js:553 Finished action keyevents.beforeStartup in 53ms with RTT 53ms; 8/4
fluxcontroller.js:553 Finished action libraries.beforeStartup in 51ms with RTT 52ms; 8/4
fluxcontroller.js:553 Finished action guides.beforeStartup in 50ms with RTT 50ms; 8/4
fluxcontroller.js:553 Finished action transform.beforeStartup in 49ms with RTT 49ms; 8/4
bluebird.js:95 Uncaught TypeError: Cannot read property 'characterStyle' of null
fluxcontroller.js:553 Finished action ui.beforeStartup in 66ms with RTT 67ms; 2/4
fluxcontroller.js:543 Executing action layers.beforeStartup after waiting 64ms; 2/3
fluxcontroller.js:553 Finished action layers.beforeStartup in 318ms with RTT 382ms; 2/3
fluxcontroller.js:543 Executing action policy.beforeStartup after waiting 380ms; 3/1
fluxcontroller.js:543 Executing action shortcuts.beforeStartup after waiting 380ms; 3/1
fluxcontroller.js:553 Finished action shortcuts.beforeStartup in 17ms with RTT 397ms; 3/1
fluxcontroller.js:553 Finished action policy.beforeStartup in 67ms with RTT 447ms; 2/1
history.js:331 Initializing history based on historyState event from ps. Object
history.js:185 Initializing history with 3 states
fluxcontroller.js:522 Enqueuing action ui.updatePanelSizes; 1/1
fluxcontroller.js:543 Executing action ui.updatePanelSizes after waiting 2ms; 2/1
fluxcontroller.js:553 Finished action documents.beforeStartup in 533ms with RTT 533ms; 2/1
fluxcontroller.js:553 Finished action ui.updatePanelSizes in 69ms with RTT 71ms; 1/1
fluxcontroller.js:543 Executing action tools.beforeStartup after waiting 599ms; 1/0
dialog.js:153 Failed to deregister dialog: datalist-weights-195 does not exist.
fluxcontroller.js:522 Enqueuing action type.initFontList; 1/0
fluxcontroller.js:522 Enqueuing action type.initFontList; 1/1
fluxcontroller.js:553 Finished action tools.beforeStartup in 168ms with RTT 767ms; 1/2
fluxcontroller.js:543 Executing action type.initFontList after waiting 22ms; 1/1
fluxcontroller.js:522 Enqueuing action ui.afterStartup; 1/1
fluxcontroller.js:522 Enqueuing action application.afterStartup; 1/2
fluxcontroller.js:522 Enqueuing action export.afterStartup; 1/3```

---

```Finished action type.initFontList in 118ms with RTT 140ms; 2/3
fluxcontroller.js:543 Executing action type.initFontList after waiting 120ms; 2/2
export.js:296 Export: Found configured port: 59596
export.js:862 Export: Generator plugin connection established
fluxcontroller.js:553 Finished action export.afterStartup in 259ms with RTT 260ms; 2/2
fluxcontroller.js:553 Finished action type.initFontList in 269ms with RTT 389ms; 1/2
fluxcontroller.js:543 Executing action ui.afterStartup after waiting 379ms; 1/1
fluxcontroller.js:553 Finished action ui.afterStartup in 12ms with RTT 391ms; 1/1
fluxcontroller.js:543 Executing action application.afterStartup after waiting 392ms; 1/0
fluxcontroller.js:522 Enqueuing action ui.updatePanelSizes; 1/0
fluxcontroller.js:553 Finished action application.afterStartup in 206ms with RTT 598ms; 1/1
fluxcontroller.js:543 Executing action ui.updatePanelSizes after waiting 3ms; 1/0
fluxcontroller.js:553 Finished action ui.updatePanelSizes in 297ms with RTT 300ms; 1/0
fluxcontroller.js:522 Enqueuing action sampler.showHUD; 0/0
fluxcontroller.js:543 Executing action sampler.showHUD after waiting 1ms; 1/0
fluxcontroller.js:563 Action sampler.showHUD failed: TypeError: Cannot read property 'characterStyle' of null
    at Object._getSourceColor (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:77:41)
    at Object._calculateSampleTypes (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:105:32)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:403:46)
From previous event:
    at Object.showHUD (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/sampler.js:390:14)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at SamplerTool.onClick (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/tools/sampler.js:102:34)
    at React.createClass._handleClick (file://./js/jsx/Scrim.jsx:53:30)
    at Object.executeDispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3311:21)
    at SimpleEventPlugin.executeDispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:17428:40)
    at forEachEventDispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3299:5)
    at Object.executeDispatchesInOrder (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3320:3)
    at executeDispatchesAndRelease (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2693:22)
    at Array.forEach (native)
    at forEachAccumulated (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:19430:9)
    at Object.EventPluginHub.processEventQueue (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2900:5)
    at runEventQueueInBatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11217:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11243:5)
    at handleTopLevelImpl (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11329:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:18402:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:9669:19)
fluxcontroller.js:522 Enqueuing action ui.onReset; 1/0
fluxcontroller.js:522 Enqueuing action menu.onReset; 2/0
fluxcontroller.js:522 Enqueuing action guides.onReset; 3/0
fluxcontroller.js:522 Enqueuing action history.onReset; 4/0
fluxcontroller.js:522 Enqueuing action keyevents.onReset; 5/0
fluxcontroller.js:522 Enqueuing action layers.onReset; 6/0
fluxcontroller.js:522 Enqueuing action export.onReset; 7/0
fluxcontroller.js:522 Enqueuing action policy.onReset; 8/0
fluxcontroller.js:522 Enqueuing action shortcuts.onReset; 8/1
fluxcontroller.js:522 Enqueuing action tools.onReset; 8/2
fluxcontroller.js:522 Enqueuing action transform.onReset; 8/3
fluxcontroller.js:522 Enqueuing action documents.onReset; 8/4
fluxcontroller.js:543 Executing action ui.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action menu.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action guides.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action history.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action keyevents.onReset after waiting 1ms; 8/5
fluxcontroller.js:543 Executing action layers.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action export.onReset after waiting 1ms; 8/5
fluxcontroller.js:543 Executing action policy.onReset after waiting 5ms; 8/4
fluxcontroller.js:553 Finished action ui.onReset in 15ms with RTT 15ms; 8/4
fluxcontroller.js:553 Finished action menu.onReset in 14ms with RTT 14ms; 8/4
fluxcontroller.js:553 Finished action guides.onReset in 13ms with RTT 13ms; 8/4
fluxcontroller.js:553 Finished action history.onReset in 12ms with RTT 12ms; 8/4
fluxcontroller.js:553 Finished action keyevents.onReset in 11ms with RTT 12ms; 8```

**Comment by iwehrman** [comment]
I'll bet the way to repro this is to sample a layer that has never been selected. @volfied: the fix may be to call `initializeLayers` in all the sample actions before doing anything?

**Comment by chadrolfs** [comment]
Good call Ian, I think you're right!  An easy repro for this is to have a doc with 2 text layers, one selected, reset DS, hit i for Sampler, mouse over non-selected layer and hit Space.

`Action sampler.showHUD failed: TypeError: Cannot read property 'characterStyle' of null`

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Looks fixed to me!
