### ISSUE TITLE
Sampler: fills set in Ds won't sample when reopened

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2573]
-In Ds, Create some shapes on a new doc
- set the fill on them to make them distinct
- save and close
- reopen and attempt to sample from the changed fill shapes
- result: sample will fail

- work around: change the color fill, and then the sampler will work

Console log error:
```Enqueuing action documents.close; 0/0
fluxcontroller.js:543 Executing action documents.close after waiting 0ms; 1/0
fluxcontroller.js:563 Action documents.close failed: TypeError: Cannot read property 'get' of null
    at Fluxxor.createStore._handleClosedGraphicDocument (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/stores/library.js:344:58)
    at Store.__handleAction__ (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:4488:16)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:167:41)
    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:1384:20
    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:1175:12
    at baseForOwn (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:1124:11)
    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:2557:13
    at Dispatcher.doDispatchLoop (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:150:4)
    at Dispatcher._dispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:139:11)
    at defaultDispatchInterceptor [as dispatchInterceptor] (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:93:4)
    at Dispatcher.dispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:117:9)
    at Object.dispatchBinder.dispatch (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/fluxxor/build/fluxxor.js:3497:21)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:413:22)
From previous event:
    at Object.disposeDocument (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:407:14)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at Object.create.transfer.value (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:387:33)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:623:29)
From previous event:
    at Object.close (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/documents.js:620:14)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at Object.throttledFn (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/synchronization.js:66:31)
    at Object._playMenuCommand (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/menu.js:236:9)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/menu.js:338:30)
    at emitEvent (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:380:50)
    at emit (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/eventEmitter/EventEmitter.js:407:21)
    at UI._menuEventHandler (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/ui.js:90:14)
bluebird.js:95 Uncaught TypeError: Cannot read property 'get' of null
fluxcontroller.js:522 Enqueuing action ui.onReset; 0/0
fluxcontroller.js:522 Enqueuing action dialog.onReset; 1/0
fluxcontroller.js:522 Enqueuing action export.onReset; 2/0
fluxcontroller.js:522 Enqueuing action guides.onReset; 3/0
fluxcontroller.js:522 Enqueuing action history.onReset; 4/0```

**Comment by volfied** [comment]
Dupe of #2572

**Comment by volfied** [comment]
@placegraphichere can you confirm this is fixed in latest master and if it's indeed a dupe of #2572?

**Comment by placegraphichere** [comment]
appears to be fixed
