### ISSUE TITLE
Adding Effect to JPG (Background layer) will throw an error

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2586]
- drop a JPG into Ds, click (+) to add an effect
- error as follows

```Finished action dialog.openDialog in 7ms with RTT 10ms; 1/0
fluxcontroller.js:522 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:522 Enqueuing action dialog.closeDialog; 1/0
fluxcontroller.js:522 Enqueuing action layerEffects.addShadow; 1/1
fluxcontroller.js:543 Executing action superselect.marqueeSelect after waiting 0ms; 1/2
fluxcontroller.js:553 Finished action superselect.marqueeSelect in 4ms with RTT 4ms; 1/2
fluxcontroller.js:543 Executing action dialog.closeDialog after waiting 3ms; 2/0
fluxcontroller.js:543 Executing action layerEffects.addShadow after waiting 3ms; 2/0
history.js:652 History state added or merged: 2
fluxcontroller.js:553 Finished action dialog.closeDialog in 51ms with RTT 54ms; 2/0
fluxcontroller.js:563 Action layerEffects.addShadow failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Apply Locking” is not currently available.
    at eval (eval at undefined, <anonymous>:1:5)
    at eval (native)
From previous event:
    at Descriptor._batchPlayImmediate (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:387:14)
    at Descriptor.batchPlay (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:519:25)
    at Descriptor.batchPlayObjects (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:544:21)
    at Object.playWithLockOverride (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/locking.js:171:27)
    at Object.playLayerActions (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/layeractions.js:125:40)
    at Object._syncStoreToPs (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/layereffects.js:103:33)
    at Object._upsertShadowProperties (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/layereffects.js:159:31)
    at Object.addShadow (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/layereffects.js:170:40)
    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:453:36)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:546:37)
From previous event:
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:542:22)
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:309:14)
    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:303:26)
From previous event:
    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:299:21)
    at AsyncDependencyQueue.push (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:525:42)
    at React.createClass.mouseUpHandler (file://./js/jsx/tools/SuperselectOverlay.jsx:389:48)
bluebird.js:95 Uncaught Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Apply Locking” is not currently available.
fluxcontroller.js:522 Enqueuing action ui.onReset; 0/0
fluxcontroller.js:522 Enqueuing action dialog.onReset; 1/0
fluxcontroller.js:522 Enqueuing action export.onReset; 2/0
fluxcontroller.js:522 Enqueuing action guides.onReset; 3/0
fluxcontroller.js:522 Enqueuing action history.onReset; 4/0
fluxcontroller.js:522 Enqueuing action keyevents.onReset; 5/0
fluxcontroller.js:522 Enqueuing action transform.onReset; 6/0
fluxcontroller.js:522 Enqueuing action menu.onReset; 7/0
fluxcontroller.js:522 Enqueuing action policy.onReset; 8/0
fluxcontroller.js:522 Enqueuing action shortcuts.onReset; 8/1
fluxcontroller.js:522 Enqueuing action tools.onReset; 8/2
fluxcontroller.js:522 Enqueuing action layers.onReset; 8/3
fluxcontroller.js:522 Enqueuing action documents.onReset; 8/4
fluxcontroller.js:543 Executing action ui.onReset after waiting 1ms; 8/5
fluxcontroller.js:543 Executing action dialog.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action export.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action guides.onReset after waiting 0ms; 8/5
fluxcontroller.js:543 Executing action history.onReset after waiting 1ms; 8/5
fluxcontroller.js:543 Executing action keyevents.onReset after waiting 0ms; 8/5```

**Comment by chadrolfs** [comment]
Quick easy repro:
File > New...
Select Document Type: Default Photoshop Size (OK)
add layer effect

`Action layerEffects.addShadow failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Apply Locking” is not currently available.`

**Comment by shaoshing** [comment]
Adding style is disabled for background layer. @placegraphichere please verify.

**Comment by placegraphichere** [comment]
fixed
