### ISSUE TITLE
Exporting assets from a modal tool state fails

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3137]
0. Make a text layer, configure at least one asset.
1. Edit the text layer.
2. Click the "export now" button in the export panel:

```
Executing action export.exportLayerAssets after waiting 1ms; 1/4
fluxcontroller.js:472 Transfer from policy.suspendAllPolicies to policy.suspendPolicies failed: Error: Policies are already suspended
    at Object.suspendPolicies (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/policy.js:245:35)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:568:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:455:37)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.FluxController._makeActionReceiver.Object.create.transfer.value (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:445:42)
    at Object.suspendAllPolicies (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/policy.js:291:36)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:568:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:455:37)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.FluxController._makeActionReceiver.Object.create.transfer.value (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:445:42)
    at Object.promptForFolder (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/export.js:663:21)
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:568:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:455:37)
```

**Comment by iwehrman** [comment]
Also, for some reason the Export Now button remains disabled after the controller resets. However, this doesn't happen after `Help > Test Action Failure`, which I guess is good news?

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify?

**Comment by chadrolfs** [comment]
not fixed.  Now when I do this, console returns a bunch of errors, including:
`Transfer from policy.suspendAllPolicies to policy.suspendPolicies failed: Error: Policies are already suspended`
`Uncaught Error: Job canceled before execution`

**Comment by mcilroyc** [comment]
stealing this from wehrman, and nominating it for 3.2

**Comment by iwehrman** [comment]
I think there are three problems:

1. The export buttons are enabled when in a modal state. They should probably just be disabled.
2. The export actions are not modal state, so in theory we should just be killing the modal state before proceeding. The problem is that we don't process the `modalToolStateChanged` event until _after_ the action (its emitted but enqueued), and that would be the time during which other the modal text policies are all restored. So, if we wanted to make this work magically, we would have to somehow run the `modalToolStateChanged` handler before proceeding. That will probably be awkward.
3. There is state in the react component which disables the export button while assets are being exported. In this case, the state is changed when the button is pressed, and then the error happens and the controller resets, and there is never an opportunity to flip the state bit back. If it's not convenient to put this state in a store, one possible workaround for this is the new `ApplicationStore` "reset" event introduced in #3582 (2a2cd7088b22ace9bc058e091d72dd81c6b424b0).

We probably just want to tackle 1 and 3 immediately.

**Comment by volfied** [comment]
@iwehrman now that #3592 is merged, you be the judge to close this or leave it open for 2.

**Comment by iwehrman** [comment]
I'm calling this FBNC. Over to @chadrolfs to verify.

**Comment by chadrolfs** [comment]
Yup.
