### ISSUE TITLE
Turning off Stroke visibility results in Unhandled rejection Error

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3202]
On compiled .js only - 

new doc, drag out a rect, turn off stroke visibility
result:
`Unhandled rejection Error: Attempt to extract key: event as: string actual type is: boolean`
  `at eval (eval at undefined, <anonymous>:1:5)`
   `at eval (native)`

CNR on release branch and master
Shipped in 16.1

**Comment by iwehrman** [comment]
This is a headlights bug. If you enable debug-time headlights logging, you get this:
```
Error: Attempt to extract key: event as: string actual type is: boolean
    at eval (eval at undefined, <anonymous>:1:5)
    at eval (native)
From previous event:
    at Object.logHeadlightsEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps.js:87:20)
    at Object.logEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/headlights.js:49:30)
    at React.createClass._toggleStrokeEnabled (file://./js/jsx/sections/style/Stroke.jsx:115:24)
    at React.createClass.handleClick (file://./js/jsx/shared/ToggleButton.jsx:95:28)
    at Object.executeDispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3311:21)
    at SimpleEventPlugin.executeDispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:17428:40)
    at forEachEventDispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3299:5)
    at Object.executeDispatchesInOrder (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3320:3)
    at executeDispatchesAndRelease (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2693:22)
    at Array.forEach (native)
    at forEachAccumulated (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:19430:9)
    at Object.EventPluginHub.processEventQueue (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2900:5)
    at runEventQueueInBatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11217:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11243:5)
    at handleTopLevelImpl (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11329:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:18402:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:9669:19)
    at Object.batchedUpdates (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:16633:20)
    at ReactEventListener.dispatchEvent (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11423:20)
```

**Comment by iwehrman** [comment]
The problem is that `isChecked` is a boolean, not a string:
https://github.com/adobe-photoshop/spaces-design/blob/51b412926ecad6aa18baedc134e2030f0756b9b2/src/js/jsx/sections/style/Stroke.jsx#L115

**Comment by iwehrman** [comment]
FBNC 2 @chadrolfs.
