### ISSUE TITLE
Error activating pen tool second time

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3311]
1. Reload Design Space with the pen tool acitve.
2. Activate to any other tool. 
3. Activate the pen tool.

Result:
```
Transfer from toolPen.select to shortcuts.addShortcut failed: Shortcut already exists: penBackspace(anonymous function) @ fluxcontroller.js:491tryCatcher @ bluebird.js:4912Promise._settlePromiseFromHandler @ bluebird.js:2997Promise._settlePromise @ bluebird.js:3054Promise._settlePromise0 @ bluebird.js:3099Promise._settlePromises @ bluebird.js:3178(anonymous function) @ bluebird.js:162setTimeout (async)schedule @ bluebird.js:133Async.settlePromises @ bluebird.js:161Promise._reject @ bluebird.js:3144Promise._settlePromise @ bluebird.js:3069Promise._settlePromise0 @ bluebird.js:3099Promise._settlePromises @ bluebird.js:3178(anonymous function) @ bluebird.js:162setTimeout (async)schedule @ bluebird.js:133Async.settlePromises @ bluebird.js:161Promise._reject @ bluebird.js:3144Promise._settlePromise @ bluebird.js:3069Promise._settlePromise0 @ bluebird.js:3099Promise._settlePromises @ bluebird.js:3178(anonymous function) @ bluebird.js:162setTimeout (async)schedule @ bluebird.js:133Async.settlePromises @ bluebird.js:161Promise._reject @ bluebird.js:3144Promise._settlePromise @ bluebird.js:3069Promise._settlePromise0 @ bluebird.js:3099Promise._settlePromises @ bluebird.js:3178(anonymous function) @ bluebird.js:162setTimeout (async)schedule @ bluebird.js:133Async.settlePromises @ bluebird.js:161Promise._reject @ bluebird.js:3144Promise._resolveCallback @ bluebird.js:2942Promise._settlePromiseFromHandler @ bluebird.js:3010Promise._settlePromise @ bluebird.js:3054Promise._settlePromiseCtx @ bluebird.js:3091(anonymous function) @ bluebird.js:152

Transfer from tools.select to toolPen.select failed: Error: Job canceled before execution
    at file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:154:33
    at Array.forEach (native)
    at AsyncDependencyQueue.removeAll (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:153:23)
    at Object.create._reset.value (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:414:35)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:372:22)
    at Map.forEach (native)
    at FluxController._resetActionReceivers (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:370:31)
    at FluxController._resetController (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:934:14)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:494:38)
From previous event:
    at new Job (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:47:28)
    at AsyncDependencyQueue.push (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:139:19)
    at Object.create.transfer.value (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:464:42)
    at Object.select (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/tool/pen.js:85:34)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:612:44)
From previous event:
    at FluxController._applyAction (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:611:14)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:474:37)
    at AsyncDependencyQueue._processNext (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.create.transfer.value (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:464:42)
    at Object.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/tools.js:465:49)
From previous event:
    at Object.selectTool (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/tools.js:459:14)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:612:44)
From previous event:
    at FluxController._applyAction (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:611:14)
    at null.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:690:29)
    at AsyncDependencyQueue._processNext (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:684:42)
    at React.createClass._handleToolbarButtonClick (file://./js/jsx/Toolbar.jsx:206:50)
    at React.createClass._handleClick (file://./js/jsx/shared/Button.jsx:45:28)
    at Object.executeDispatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3311:21)
    at SimpleEventPlugin.executeDispatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:17428:40)
    at forEachEventDispatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3299:5)
    at Object.executeDispatchesInOrder (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3320:3)
    at executeDispatchesAndRelease (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2693:22)
    at Array.forEach (native)
    at forEachAccumulated (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:19430:9)
    at Object.EventPluginHub.processEventQueue (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2900:5)
    at runEventQueueInBatch (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11217:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11243:5)
    at handleTopLevelImpl (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11329:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (file:///Users/ian/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:18402:20)
```

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify.

**Comment by iwehrman** [comment]
Does that mean you get the same error, @chadrolfs?

**Comment by chadrolfs** [comment]
not fixed.  errors on step 1 above.

**Comment by chadrolfs** [comment]
as soon as you reload with pen tool

**Comment by chadrolfs** [comment]
`Transfer from tools.select to toolPen.select failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Deselect” is not currently available.`

**Comment by iwehrman** [comment]
I do not see that. Also, you're seeing a different error message, so I assume this is a different bug. Do you need to be in any particular state to repro?

**Comment by iwehrman** [comment]
This seems to be related to masks. It only triggers when loading with the pen tool and without an active document.

**Comment by iwehrman** [comment]
Also, this repros in PS 16.1. I think we should prepare a 16.1.1 patch for this.

**Comment by iwehrman** [comment]
This is the offending line: https://github.com/adobe-photoshop/spaces-design/blob/6a130737d9afc13f926c658e244ea9612e0d488d/src/js/actions/tool/pen.js#L93

**Comment by iwehrman** [comment]
Opened #3329 for the new bug. This one is FBNC to @chadrolfs again.
