### ISSUE TITLE
Startup failure with pen tool and no doc

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3329]
1. From standard PS, select the pen tool
2. Switch to Design Space.

Result: complete failure.
```
Transfer from tools.select to toolPen.select failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Deselect” is not currently available.
    at eval (eval at undefined, <anonymous>:1:1)
    at eval (native)
From previous event:
    at Descriptor._batchPlayImmediate (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:394:14)
    at Descriptor.batchPlay (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:526:25)
    at Descriptor.batchPlayObjects (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:551:21)
    at Descriptor.playObject (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/spaces-adapter/src/ps/descriptor.js:374:21)
    at Object.select (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/tool/pen.js:93:43)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:612:44)
From previous event:
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:611:14)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:474:37)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.create.transfer.value (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:464:42)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/tools.js:470:49)
From previous event:
    at Object.selectTool (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/tools.js:464:14)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:612:44)
From previous event:
    at FluxController._applyAction (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:611:14)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:690:29)
    at AsyncDependencyQueue._processNext (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)
    at AsyncDependencyQueue.push (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:684:42)
    at React.createClass._handleToolbarButtonClick (file://./js/jsx/Toolbar.jsx:206:50)
    at React.createClass._handleClick (file://./js/jsx/shared/Button.jsx:45:28)
    at Object.executeDispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3311:21)
    at SimpleEventPlugin.executeDispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:17428:40)
    at forEachEventDispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3299:5)
    at Object.executeDispatchesInOrder (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:3320:3)
    at executeDispatchesAndRelease (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2693:22)
    at Array.forEach (native)
    at forEachAccumulated (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:19430:9)
    at Object.EventPluginHub.processEventQueue (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:2900:5)
    at runEventQueueInBatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11217:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11243:5)
    at handleTopLevelImpl (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:11329:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/react/react-with-addons.js:18402:20)
```

More details are at the bottom of #3311.

**Comment by iwehrman** [comment]
The offending line: https://github.com/adobe-photoshop/spaces-design/blob/6a130737d9afc13f926c658e244ea9612e0d488d/src/js/actions/tool/pen.js#L93

**Comment by mcilroyc** [comment]
Assigning to @chadrolfs to validate

**Comment by iwehrman** [comment]
We might want to leave this open until it's been fixed on the release branch.

**Comment by iwehrman** [comment]
Back to @pineapplespatula for the release fix as well.

**Comment by chadrolfs** [comment]
logged for 16.1.1 approval: https://watsonexp.corp.adobe.com/#bug=4095576
