### ISSUE TITLE
Error activating document: could not amend history, document not properly initialized

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3595]
I've hit this twice today, but I can't repro reliably. I suspect it has something to do with selecting a document the first time (i.e., selecting an uninitialized document). 
```
Enqueuing action tools.resetBorderPolicies; 1/0
Finished action layers.select in 87ms with RTT 87ms; 1/1
Executing action tools.resetBorderPolicies after waiting 13ms; 1/0
Finished action tools.resetBorderPolicies in 5ms with RTT 18ms; 1/0
Enqueuing action documents.selectDocument; 0/0
Executing action documents.selectDocument after waiting 0ms; 1/0
Enqueuing action tools.resetBorderPolicies; 1/0
Transfer from layers.resetLinkedLayers to layers.resetBounds failed: Error: Could not amend history, document not properly initialized: 281
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/spaces-design-en.js:87495:28)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:93693:13)
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:94914:20
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:94705:12
    at baseForOwn (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:94654:11)
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:96087:13
    at Dispatcher.doDispatchLoop (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:93680:4)
    at Dispatcher.doDispatchLoop (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:93721:11)
    at Dispatcher._dispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:93669:11)
    at defaultDispatchInterceptor [as dispatchInterceptor] (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:93623:4)
    at Dispatcher.dispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:93647:9)
    at Object.dispatchBinder.dispatch (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:97027:21)
    at Object.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/spaces-design-en.js:57606:23)
From previous event:
    at Object.resetBounds (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/spaces-design-en.js:57593:15)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/spaces-design-en.js:78061:45)
    at tryCatcher (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:5091:24)
    at Promise._settlePromiseFromHandler (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:3155:32)
    at Promise._settlePromise (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:3212:19)
    at Promise._settlePromiseCtx (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:3249:11)
    at file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:265:21
    at MutationObserver.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/externalDeps.js:4389:14)
```

**Comment by iwehrman** [comment]
I haven't seen this lately. Can you try to repro @chadrolfs?

**Comment by chadrolfs** [comment]
I CNR
