### ISSUE TITLE
Error creating new document

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3630]
On master at 55237842f75d3bc8c409fb12cd9263c4009c956e with Mac pgdev.1016 I'm seeing an error every time I create a new document with cmd-N:

```
Enqueuing action documents.createNew; 0/0
Executing action documents.createNew after waiting 0ms; 1/0
Initializing history based on historyState event from ps. Object
Initializing history with 2 states
Transfer from documents.createNew to export.addDefaultAsset failed: Error: Can not find document undefined to addDefaultAsset
    at Object.addDefaultAsset (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/spaces-design-en.js:64063:36)
    at null.<anonymous> (file:///Users/wehrman/Desktop/photoshop-Release_x86_64/Plug-Ins/Spaces/www/build/spaces-design-en.js:79495:45)
```

**Comment by iwehrman** [comment]
This is due to a recent core issue, tracked here:
https://jira.corp.adobe.com/browse/PS-1109

**Comment by iwehrman** [comment]
Fixed in Mac pgdev.1020 by CL 1061111.
